FROM ubuntu:latest

COPY Script.sh /usr/local/bin/Script.sh

RUN chmod +x /usr/local/bin/Script.sh

RUN /usr/local/bin/Script.sh

RUN echo "Inicio de script" && \
    echo "Ejecutando tarea 1" && \
    echo "Ejecutando tarea 2" && \
    echo "Script finalizado."